### ISSUE TITLE
Cannot use interactive mode for more than one URL

### ISSUE THREAD

**Issue by Dentyr** [Sebbs128/STAHP#6]
Problem:
After running interactive mode and entering an URL, this error is returned:
Error: Trying to run one or more interactive functions concurrently. Operations with dynamic displays (e.g. a prompt and a progress display) cannot be running at the same time. 
![image](https://user-images.githubusercontent.com/74077896/169669550-4819acc9-8314-4783-ac95-428bb81a1dd0.png)

How to reproduce:
1) run interactive more
2) input any valid URL

Environment: 
Windows 10 64x powershell
.NET 6.0.300

**Comment by Sebbs128** [comment]
Thanks Dentyr. The error occurs because I forgot to cancel the status indicator when the end of the results is reached since switching to using IAsyncEnumerable.

Fix has just been pushed.
